# Screen releated constants
SCREEN_WIDTH = 1336
SCREEN_HEIGHT = 768

# Temporary
GROUND = SCREEN_HEIGHT - 150
JUMP_HEIGHT = GROUND - 200

# Constants
LEFT = 1
RIGHT = 0

# Base stats for player
PLAYER_HP = 500
PLAYER_MANA = 50
PLAYER_STAMINA = 800
PLAYER_SPEED = 3
JUMP_SPEED = 10